version: '3.8'

x-template: &flyway-template
  image: flyway/flyway:7.5.0

services:
  db-migrator:
    build:
      context: ./migrate
      dockerfile: Dockerfile
    command: -url="jdbc:postgresql://db:5432/sample?sslmode=disable" -user="postgres" -password="password" -connectRetries=60 migrate
    links:
      - db
    volumes:
      - ./migrate/migrations:/flyway/sql

  db:
    image: postgres:11.5
    environment:
      POSTGRES_DB: sample
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 5432:5432
