version: '3.8'

x-template: &flyway-template
  image: flyway/flyway:7.5.0

services:
  db-migrator:
    build:
      context: ./migrate
      dockerfile: Dockerfile
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: sample
    command: -url="jdbc:postgresql://db:5432/sample?sslmode=disable" -user="postgres" -password="password" -connectRetries=60
    links:
      - db
    volumes:
      - ./migrate/migrations:/flyway/sql

  db:
    image: postgres:11.5
    environment:
      POSTGRES_DB: sample
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    links:
      - db
    volumes:
      - ./backend:/go/src/app
      - api_go_modules:/go/pkg/mod
volumes:
  db-data:
    driver: local
  api_go_modules:
    driver: local
