// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// ポスト作成引数
type NewPost struct {
	// タイトル
	Title string `json:"title"`
}

// 投稿
type Post struct {
	// ID
	ID string `json:"id"`
	// タイトル
	Title string `json:"title"`
	// 投稿者
	Author *User `json:"author"`
}

// ユーザー
type User struct {
	// ID
	ID string `json:"id"`
	// 名前
	Name string `json:"name"`
}
